### PR TITLE
separate example using view for more efficeint memory,

### PR DESCRIPTION
**Pull request by dehann**
- colour map is still wrong, but likely relating to the camera driver and the mapping of bits and colours.

@Affie, note the use of `view(A, :, :, 1)` over `A[:,:,1]` to avoid allocating more memory. See more [documentation on views here](https://docs.julialang.org/en/stable/stdlib/arrays/#Views-(SubArrays-and-other-view-types)-1).

EDIT:
v4l_jl_ps3_img

### CODE REVIEW

**Comment by dehann** [comment]
v4l_jl_ps3_img

**Comment by dehann** [comment]
Hallo, I don't have a PS3eye with me right now, but internal webcam at `(1280,720)` resolution with
```julia
using Images, ImageView
using Video4Linux

function displaylive!(im1, vidchan)
    A =  take!(vidchan)
    im1 = RGB.(YCbCr.(A[:,:,1], A[:,:,2], A[:,:,3]))
    imshow(canvas["gui"]["canvas"], im1)
end
# This colour mapping may be wrong for the PS3eye.
ycrcb = Video4Linux.YUYV(1280,720)
vidchan = Channel((c::Channel) -> videoproducer(c, ycrcb, devicename = "/dev/video0", iomethod = Video4Linux.IO_METHOD_MMAP ))
#capture one frame to create im1 and canvas needed to diplay
A =  take!(vidchan)
im1 = RGB.(YCbCr.(view(A,:,:,1), view(A,:,:,2), view(A,:,:,3)))
canvas = imshow(im1)
while isopen(vidchan)
    displaylive!(im1, vidchan)
end
```
gives this:
screenshot from 2017-12-11 22-20-29

Although I still think I am doing something wrong on my end. Is there a way to see what the encoding of `A` is? I see the type as:
```julia
julia> A
720×1280×3 Array{UInt8,3}:
```

**Comment by dehann** [comment]
If the 'noise' in the image (as shown) is smaller than the full bitmap size, then maybe there is some kind of compression (jpeg or other) on the data which has not been unpacked yet?
EDIT: I'll have to try on a PS3eye tomorrow since we know that is not compressed.

**Comment by Affie** [comment]
I think you are correct assuming compression. Currently I do not think there is a need to implement compression/decompression as VideoIO.jl already deals with that. 
no ioctl functions are implemented yet, (we shoud maybe only look at basic control as the aim of this package is to provide low level access and there exist better ways and libraries to make ioctl easier)
refer to the device setup section of the readme:
No automatic setup is currently performed but there are utilities to make this easy: qv4l2 (install with: sudo apt-get install qv4l2) qv4l2 provides a gui of the ioctl of the device. Settings such as frame size and capture format can easily be changed.
If the device supports it, ons should be able to change the format from compression to raw.
One can also use `sudo apt-get install v4l2-utils`
`v4l2-ctl --device=0 --list-formats`

**Comment by dehann** [comment]
I tried `examples/ps3eye.jl` with a PS3eye and got this (it works, thanks!):
screenshot from 2017-12-12 22-13-00
cc @GearsAD

**Pull request merged**
